### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by rudotriton** [lentz/youtube-shuffle#28]
Someone brought this project to my attention, and asked how they could use it, however I am not 100% sure how it works and what the end result of running this is. A short readme would be helpful for this. I can see that I'd need a `.env` file and can probably populate some variable in there, but not all. Thanks.

**Comment by lentz** [comment]
Hey @rudotriton, I've added a README that hopefully contains the information you're seeking, depending on whether you just want to use the app, or run it yourself.

**Comment by rudotriton** [comment]
That is perfect, thank you so much!
